name: .NET

on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Check out source
      uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build with msbuild
      run: dotnet msbuild -property:Configuration=Release
    - name: Pack for nuget
      run:
        dotnet pack --configuration Release --no-restore
