name: .NET

on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Check out source
      uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build with msbuild
      run: |
         cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
         .\MSBuild.exe $env:GITHUB_WORKSPACE\src\${{ github.event.repository.name }}.csproj
    - name: Pack for nuget
      run:
        dotnet pack --configuration Release --no-restore
